### PR TITLE
Fix Version being set globally  

### PR DESCRIPTION
**Pull request by waynehoover**
0.2.0 has a bug where `Version` is set globally through the whole rails app.

This was causing my app problems because I have a rails model named `Version` and instead of giving me an AR model it was giving me a string "0.2.0", which is caused by this gem.

I have fixed this by updating the gemspec to be more inline with how must gems lay it out.

### CODE REVIEW

**Comment by grosser** [comment]
I don't see how this can fix anything, can you add a testcase that would otherwise fail ?

```

1.9.3p392 :001 > module A; VERSION = Version = 1;end
 => 1
1.9.3p392 :002 > Version
NameError: uninitialized constant Version
    from (irb):2
    from /Users/mgrosser/.rvm/rubies/ruby-1.9.3-p392/bin/irb:16:in `<main>'
1.9.3p392 :003 > VERSION
NameError: uninitialized constant VERSION
    from (irb):3
    from /Users/mgrosser/.rvm/rubies/ruby-1.9.3-p392/bin/irb:16:in `<main>'
1.9.3p392 :004 >
```

**Comment by grosser** [comment]
Ohhhhh because it includes ArMerge into activerecord...

**Comment by grosser** [comment]
but still your pull does not fix that, but doing something like extracting everything that needs to be included and then  `include ArMerge::Extension` could do the trick

**Comment by waynehoover** [comment]
Not defining `Version` fixes the problem I was having in my app.

I can put up a quick rails app that demonstrates the problem if you like. version 0.1.3 of this gem doesn't seem to have this problem which lead me to conclude that it was the gemspec that was causing the problem as that is all that seemed to change between versions that could affect things.

**Comment by grosser** [comment]
0.3.0 should fix that! (also found a bug on rails 4 so if you plan to upgrade, try to fix that first ;) )

**Pull request closed without merging**
